theme: jekyll-theme-slate
title: Welcome to Biz Aldana's homepage!
description: The purpose of this page is to showcase the skills I have gained as a student of Computer Science and Southern New Hampshire University
